### ISSUE TITLE
Write to storage request does not work

### ISSUE THREAD

**Issue by zerg1971** [heroiclabs/nakama-java#14]
Write to storage request does not work. 

For example this code (from Nakama's documentation at https://heroiclabs.com/docs/storage-collections/ ) prints empty acks.getAcksList())
```
String saveGame = "{ \"progress\": 50 }";
String myStats = "{ \"skill\": 24 }";
StorageObjectWrite saveGameObject = new StorageObjectWrite("saves", "savegame", saveGame, PermissionRead.OWNER_READ, PermissionWrite.OWNER_WRITE);
StorageObjectWrite statsObject = new StorageObjectWrite("stats", "skills", myStats, PermissionRead.OWNER_READ, PermissionWrite.OWNER_WRITE);
StorageObjectAcks acks = client.writeStorageObjects(session, saveGameObject, statsObject).get();
System.out.format("Stored objects %s", acks.getAcksList());    
```
result:
```
Stored objects []
```

and after that request table "storage" in CocroachDB is empty

UPDATE:
versions:
nakama-java: 2.0.0-SNAPSHOT, https://github.com/heroiclabs/nakama-java/commit/ed8a11e7de6396a448d5c3fce01dedebfa99889e
nakama-server: official docker image heroiclabs/nakama:2.2.0

**Comment by mofirouz** [comment]
I believe I have fixed this issue here: https://github.com/heroiclabs/nakama-java/commit/991d78b21dfc768fcda8dce5d1399f952e1341b7

Could you pull and try again?

**Comment by zerg1971** [comment]
yes, all right, thank you !

```
Stored objects [# com.heroiclabs.nakama.api.StorageObjectAck@29abb7a9
collection: "saves"
key: "savegame"
user_id: "0b7f1aa0-0c2d-47b3-97a3-42262ed42147"
version: "75a177ee7ee93afa2c7b9bea4dc23269", # com.heroiclabs.nakama.api.StorageObjectAck@94387b19
collection: "stats"
key: "skills"
user_id: "0b7f1aa0-0c2d-47b3-97a3-42262ed42147"
version: "62109687a7cc23c0e8082cfbe7791852"]
```
