### ISSUE TITLE
UserPresence is always empty in MatchData

### ISSUE THREAD

**Issue by metaphore** [heroiclabs/nakama-java#25]
When I send messages between clients withing the same match, they receive them just fine in `SocketListener#onMatchData(MatchData)`. The only problem is I always get null in `MatchData#userPresence` on the receiving end.

I send messages with `WebSocketClient#sendMatchData(String, long, byte[])`.
Am I doing something wrong?

_Nakama 2.5.1_
_Nakama Java 2.0.1_

**Comment by zyro** [comment]
@metaphore Issues are not the best place to ask questions, they're typically used to raise and tracked confirmed problems. You should head over to our [community channel](https://gitter.im/heroiclabs/nakama) for general questions.

For now though, are you using an authoritative or relayed multiplayer match?

**Comment by metaphore** [comment]
@zyro sorry about that, will keep in mind for future cases.

I follow instructions from [Realtime Multiplayer ](https://heroiclabs.com/docs/gameplay-multiplayer-realtime/) documentation section.

**Comment by mofirouz** [comment]
Fixed in https://github.com/heroiclabs/nakama-java/commit/2222f178a6ed971d16ce3c7ab1474bb44a5f6453
