### ISSUE TITLE
Upload library into central repositories and make it downloadable via Gradle.

### ISSUE THREAD

**Issue by m3doune** [heroiclabs/nakama-java#27]
Using Gradle download version 0.5 instead of 2.0.*. Can you update this, please?

**Comment by mofirouz** [comment]
Thanks a lot for the reminder @m3doune - The precursor task to this is updating the client library to use the latest Gradle 5 build system. 

For the time being, please consider downloading the library directly from GitHub.

**Comment by lugehorsam** [comment]
Hey @m3doune , we've updated to Gradle 6.5 - this SDK is downloadable directly from Github via JitPack (see README).
