### ISSUE TITLE
How to send data in real time in Java class library like SDK

### ISSUE THREAD

**Issue by hyb1234hi** [heroiclabs/nakama-java#30]
We can use JavaScript client  exchange data as follows:
socket.onchannelmessage = (channelMessage) => {
  console.info("Received chat message:", channelMessage);
};

const channelId = "pineapple-pizza-lovers-room";
var response = await socket.send({ channel_join: {
  type: 1, // 1 = room, 2 = Direct Message, 3 = Group
  target: channelId,
  persistence: false,
  hidden: false
} });
console.info("Successfully joined channel:", response.channel.id);

const messageAck = await socket.send({ channel_message_send: {
  channel_id: response.channel.id,
  content: {"message": "Pineapple doesn't belong on a pizza!"}
} });
console.info("Successfully sent chat message:", messageAck);

How to send data in real time in Java class library like this.

**Comment by novabyte** [comment]
@hyb1234hi I think this conversation should be moved to the forums as a question on [there](https://forum.heroiclabs.com/). The issue tracker is for errors or problems with the client sdk. Thanks
