### ISSUE TITLE
Incompatible dependencies between Firestore and Nakama android Client

### ISSUE THREAD

**Issue by hament9193** [heroiclabs/nakama-java#31]
Issue in using Nakama client on android project along with FireStore. There are common dependencies between the two, But Nakama client libs are older which are not compatible anymore. Sample android project with the issue : https://github.com/hament9193/NakamaFirestoreClient

<img width="1338" alt="Screenshot 2020-01-22 at 10 07 18 AM" src="https://user-images.githubusercontent.com/9552261/72866133-4b3ffb00-3d00-11ea-82c1-973f12e87442.png">

**Comment by mofirouz** [comment]
Thanks for putting together this example. Seems like we’d likely need to update the dependencies of the client SDK. 

Is this something you can tackle as part of a PR since you have working knowledge of the what’s clashing between the two SDKs?

**Comment by mofirouz** [comment]
Can you also tell me what dependencies in nakama-java codebase are causing this clash?

**Comment by hament9193** [comment]
FireStore dependencies:
'com.google.firebase:protolite-well-known-types:17.0.0'
'com.google.protobuf:protobuf-lite:3.0.1'
'io.grpc:grpc-protobuf-lite:1.21.0'
'com.google.errorprone:error_prone_annotations:2.3.2'
'io.grpc:grpc-api:1.21.0'
'io.grpc:grpc-core:1.21.0'
'io.grpc:grpc-okhttp:1.21.0'
'io.grpc:grpc-stub:1.21.0'

Nakama dependencies:
'com.google.protobuf:protobuf-java:3.4.0'
'io.grpc:grpc-protobuf-lite:1.14.0'
'com.google.errorprone:error_prone_annotations:2.2.0'
'io.grpc:grpc-api:1.14.0'
'io.grpc:grpc-core:1.14.0'
'io.grpc:grpc-okhttp:1.14.0'
'io.grpc:grpc-stub:1.14.0'

**Comment by mofirouz** [comment]
Thanks for this - this is fixed on https://github.com/heroiclabs/nakama-java/commit/46ba09b80bbabdabd84808c4fb6f7680bb7aec04 and is available in release v2.0.4.
