### ISSUE TITLE
Duplicate class

### ISSUE THREAD

**Issue by karan1213** [heroiclabs/nakama-java#45]
I am getting a Duplicate class warnings and can't compile the Android project

Here is how I implemented the Gradle file
...
    configurations {
        mplementation.exclude module:'proto-google-common-protos'
        implementation.exclude module:'protolite-well-known-types'
        implementation.exclude module:'protobuf-lite'
        implementation.exclude module:'protobuf-java'
    }
...
implementation ('com.github.heroiclabs:nakama-java:3dde5b3baf'){
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }

Here are the logs
Duplicate class com.heroiclabs.nakama.AbstractSocketListener found in modules jetified-nakama-java-3dde5b3baf.jar (com.github.heroiclabs.nakama-java:nakama-java:3dde5b3baf) and jetified-nakama-java-all-3dde5b3baf.jar (com.github.heroiclabs.nakama-java:nakama-java-all:3dde5b3baf)
Duplicate class com.heroiclabs.nakama.Channel found in modules jetified-nakama-java-3dde5b3baf.jar (com.github.heroiclabs.nakama-java:nakama-java:3dde5b3baf) and jetified-nakama-java-all-3dde5b3baf.jar (com.github.heroiclabs.nakama-java:nakama-java-all:3dde5b3baf)
Duplicate class com.heroiclabs.nakama.ChannelJoinMessage found in modules jetified-nakama-java-3dde5b3baf.jar (com.github.heroiclabs.nakama-java:nakama-java:3dde5b3baf) and jetified-nakama-java-all-3dde5b3baf.jar (com.github.heroiclabs.nakama-java:nakama-java-all:3dde5b3baf)
Duplicate class com.heroiclabs.nakama.ChannelLeaveMessage found in modules jetified-nakama-java-3dde5b3baf.jar (com.github.heroiclabs.nakama-java:nakama-java:3dde5b3baf) and jetified-nakama-java-all-3dde5b3baf.jar (com.github.heroiclabs.nakama-java:nakama-java-all:3dde5b3baf)
Duplicate class com.heroiclabs.nakama.ChannelMessage found in modules jetified-nakama-java-3dde5b3baf.jar (com.github.heroiclabs.nakama-java:nakama-java:3dde5b3baf) and jetified-nakama-java-all-3dde5b3baf.jar (com.github.heroiclabs.nakama-java:nakama-java-all:3dde5b3baf)
Duplicate class com.heroiclabs.nakama.ChannelMessageAck found in modules jetified-nakama-java-3dde5b3baf.jar (com.github.heroiclabs.nakama-java:nakama-java:3dde5b3baf) and jetified-nakama-java-all-3dde5b3baf.jar (com.github.heroiclabs.nakama-java:nakama-java-all:3dde5b3baf)

**Comment by lugehorsam** [comment]
@karan1213 it appears that both the fat jar and the regular jar that we distribute our getting included in your build.

`implementation ('com.github.heroiclabs:nakama-java:3dde5b3baf')` shows you are just including the regular jar, which is fine. Is there somewhere else in your Gradle file that you could be including the Nakama fat jar? It has the `-all` suffix that you see in your logs.

**Comment by karan1213** [comment]
@lugehorsam No, this single statement add both nakama-java & nakama-java-all


![image](https://user-images.githubusercontent.com/5412693/94482550-15d89f00-01f7-11eb-8060-21f8bb9f7ada.png)

**Comment by lugehorsam** [comment]
@karan1213 can you share your gradle version and the command you are using to build the gradle project?

Could you also run a clean on your build? 

The following `build.gradle` results in a successful build for me:


```/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

plugins {
    id 'application'
    id 'java'
}

configurations {
    implementation.exclude module:'proto-google-common-protos'
    implementation.exclude module:'protolite-well-known-types'
    implementation.exclude module:'protobuf-lite'
    implementation.exclude module:'protobuf-java'
}

repositories {
    maven {
        url 'https://jitpack.io'
    }

    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation ('com.github.heroiclabs:nakama-java:3dde5b3baf8e71ae9655ac31f2ccd56f1c4a649e') {
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }
}


application {
    mainClass = 'Main'
}
```

**Comment by karan1213** [comment]
@lugehorsam 
I am using Android Studio to run the project
My project includes Google Play services and Firebase SDK

Do you think Firebase SDK might be causing the issue?

Here are the dependencies

dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:4.3.3'

        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$versions.kotlin"
        classpath 'com.google.firebase:perf-plugin:1.3.1'

        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.13'
    }

**Comment by lugehorsam** [comment]
@karan1213 no I think it's the because something about the Android Studio setup is including both Nakama .jar files for some reason, as I mentioned above. I can take a look tomorrow, but it would help me if you could share your complete build scripts (all `build.gradle` and any scripts specific to Android studio.)

**Comment by lugehorsam** [comment]
@karan1213 thanks again for filing this issue - we've resolved it in the latest commit.

Updating your .gradle file with the following dependency should do the trick: `com.github.heroiclabs:nakama-java:724d882ef46bca2d685943f1d712729e8a7c4dff`
