### ISSUE TITLE
JitPack release tags are not working. 

### ISSUE THREAD

**Issue by Mir1001** [heroiclabs/nakama-java#50]
Please check what is wrong. JitPack reports errors on the last tags. 

![image](https://user-images.githubusercontent.com/623148/104848927-57e13a00-58e7-11eb-957d-a3c6fc065ac4.png)

**Comment by lugehorsam** [comment]
@Mir1001 we've yet to do a new official release supporting Jitpack but if you take the latest commit off our master, that should work fine.

We'll do a new release next week to clear up confusion about this.

**Comment by lugehorsam** [comment]
@Mir1001 we've done a new official release supporting JitPack. This will allow you to pull in our Jitpack package by version string rather than just commit.

https://github.com/heroiclabs/nakama-java/releases/tag/v2.1.0
