### ISSUE TITLE
Not Able to Connect to Server via SocketClient.

### ISSUE THREAD

**Issue by ANURAGX** [heroiclabs/nakama-java#54]
Hi,
As the docs here https://heroiclabs.com/docs/android-java-client-guide/
I tried to connect to the server via socket but its not connecting, I m not getting callback for connect either **success** or **failure**.

Below is the activity I added in the nakama-android-example.
`public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(@Nullable @org.jetbrains.annotations.Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        String myAWSIP = "";
        final DefaultClient client = new DefaultClient("defaultkey", myAWSIP, 7349, false);
        final ExecutorService executor = Executors.newSingleThreadExecutor();

        try {
            String email = "super@heroes.com";
            String password = "batsignal";
            Futures.addCallback(client.authenticateEmail(email, password), new FutureCallback<Session>() {
                @Override
                public void onSuccess(final Session result) {
                    Log.d("NAMAKA_TAG", "got session: " + result.getAuthToken());
                    System.out.println("got session: " + result.getAuthToken());
                    SocketClient socketClient = client.createSocket();

                    Futures.addCallback(socketClient.connect(result, new AbstractSocketListener() {}), new FutureCallback<Session>() {
                        @Override
                        public void onSuccess(@org.jetbrains.annotations.Nullable Session result) {
                            Log.d("NAMAKA_TAG", "Socket Created " + result.toString());
                        }

                        @Override
                        public void onFailure(Throwable t) {
                            Log.d("NAMAKA_TAG", "Socket Creation failed " + t.toString());
                        }
                    }, executor);

                    //executor.shutdown();
                }

                @Override
                public void onFailure(final Throwable throwable) {
                    System.out.println(throwable.getMessage());
                    Log.d("NAMAKA_TAG", throwable.getLocalizedMessage());
                    //executor.shutdown();
                }
            }, executor);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            Log.d("NAMAKA_TAG", e.getMessage());
        }
    }
}` 

But for some reason I m not getting any callback success or failure for connect.

**Comment by lugehorsam** [comment]
Hey @ANURAGX, thanks for filing this issue -- we just did a patch release to fix this. Please give it a try and let me know how it fares.

https://github.com/heroiclabs/nakama-java/releases/tag/v2.1.3

**Comment by ANURAGX** [comment]
@lugehorsam Yes it works now and my socket is connecting.
Thanks for quick resolution.
