### ISSUE TITLE
The latest version （v2.1.2） of nakama java client jar package has dependency problems

### ISSUE THREAD

**Issue by yaohuiwu** [heroiclabs/nakama-java#55]
I saw from https://jitpack.io/com/github/heroiclabs/nakama-java/ that the latest version of java client is v2.1.2, when I use the following method to import the jar package of this version:

    <repositories>
      <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
      </repository>
    </repositories>

      <dependency>
        <groupId>com.github.heroiclabs.nakama-java</groupId>
        <artifactId>nakama-java</artifactId>
        <version>v2.1.2</version>
        <type>jar</type>
      </dependency>

The code in src/main/java cannot be compiled, and it prompts that the class in com.google.protobuf:protobuf-javalite cannot be found.

![image](https://user-images.githubusercontent.com/7850789/112921933-34840800-913e-11eb-9f93-6a12d4c18101.png)

 The code in src/test/java can run normally.
![image](https://user-images.githubusercontent.com/7850789/112922005-51204000-913e-11eb-8169-76f75359249d.png)

At present, I solve it by explicitly introducing the com.google.protobuf:protobuf-javalite dependency in pom.xml, but I think this is unnecessary.

    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-javalite</artifactId>
      <version>3.13.0</version>
    </dependency>

**Comment by yaohuiwu** [comment]
I think the problem may be that the scope of com.google.protobuf:protobuf-javalite should be **compile** instead of **runtime**. Because Account inherits GeneratedMessageLite, if Account is used in the client code, it will inevitably rely on the com.google.protobuf:protobuf-javalite package when compiling.

**Comment by mofirouz** [comment]
Have you tried the solution on this mentioned here: https://github.com/heroiclabs/nakama-java/issues/52#issuecomment-792811909

**Comment by yaohuiwu** [comment]
I have solved the problem by explicitly introducing the com.google.protobuf:protobuf-javalite dependency with compile scope in my pom.xml.

But I don't think what i did is necessary. The scope of protobuf-javalite dependency introduced by nakama-java should be compile not runtime.
@mofirouz

**Comment by lugehorsam** [comment]
Thanks @yaohuiwu this is now fixed in the latest release so you can remove your temporary fix. https://github.com/heroiclabs/nakama-java/releases/tag/v2.1.4

**Comment by yaohuiwu** [comment]
I updated to v2.1.4 and remove the temporary fix. It works well. Great!
