### ISSUE TITLE
Cannot access 'com.google.protobuf.GeneratedMessageLite' which is a supertype of 'com.heroiclabs.nakama.api.ChannelMessage'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by Allan-Nava** [heroiclabs/nakama-java#58]
I this problem: 

`Cannot access 'com.google.protobuf.GeneratedMessageLite' which is a supertype of 'com.heroiclabs.nakama.api.ChannelMessage'. Check your module classpath for missing or conflicting dependencies`

<img width="873" alt="Screenshot 2021-04-07 at 12 43 52" src="https://user-images.githubusercontent.com/22498435/113854388-1bfb9980-979f-11eb-89bd-4a811e38afa0.png">

**Comment by lugehorsam** [comment]
Thanks @Allan-Nava this is now fixed in the latest relase: https://github.com/heroiclabs/nakama-java/releases/tag/v2.1.4

**Comment by Allan-Nava** [comment]
> Thanks @Allan-Nava this is now fixed in the latest relase: https://github.com/heroiclabs/nakama-java/releases/tag/v2.1.4

Perfect now I will try! Thank you for replying so quickly
