### ISSUE TITLE
Configuration 'compile' is obsolete

### ISSUE THREAD

**Issue by FalconJ** [heroiclabs/nakama-java#8]
In my Gradle output I get the following warning:

`Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
`
Just a friendly reminder to update the configuration for the release of 2.0.0.

**Comment by novabyte** [comment]
Thanks @FalconJ. We also need to update this client for the new major release of Nakama so we'll work on the tasks in parallel.

**Comment by mofirouz** [comment]
We should upgrade to Gradle 5 and use the latest build system. This is tracked in #28.
