### ISSUE TITLE
Update to support Nakama 2

### ISSUE THREAD

**Issue by mofirouz** [heroiclabs/nakama-java#9]
Please leave a comment (or emoji 😄 ) if you'd like us to update this client to Nakama 2.

**Comment by FalconJ** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png)

**Comment by blacklightknight** [comment]
😄

**Comment by shawnt1990** [comment]
😄

**Comment by XPDT1** [comment]
😄

**Comment by drone-ah** [comment]
:)

**Comment by bkollc** [comment]
😄

**Comment by saragames** [comment]
Ok

**Comment by formatCvt** [comment]
:fire:

**Comment by TheLaughingMan4** [comment]
😄

**Comment by OmidMahmoudi** [comment]
![image](https://user-images.githubusercontent.com/19889603/43900018-e05453ee-9bf8-11e8-9f31-0086afefd545.png)
![image](https://user-images.githubusercontent.com/19889603/43900018-e05453ee-9bf8-11e8-9f31-0086afefd545.png)

**Comment by ahmedk92** [comment]
😄

**Comment by SayedArfa** [comment]
😄

**Comment by zerg1971** [comment]
+1

**Comment by mohsenyz** [comment]
:smile_cat:

**Comment by mofirouz** [comment]
The Java client is actually completely compatible with Nakama 2 already - however we've not had the chance to configure various release management tools (maven central, jcenter etc) and publish a full release. If you want a pre-release, jump on [Gitter](https://gitter.im/heroiclabs/nakama) and DM me and I'll give you a precompiled JAR file.

The documentation on the website is for Nakama 2 client as well.

**Comment by mofirouz** [comment]
I'm leaving this open until we actually finalise the release.

**Comment by mofirouz** [comment]
We've released v2.0.0 of Nakama Java client:
https://github.com/heroiclabs/nakama-java/releases/tag/v2.0.0
